language: python

sudo: required

services:
  - docker

python:
  - 3.6
install:
  - cd bme590_melanoma_detection
  - docker-compose build
  - docker-compose up -d
# Activate your environment NOTE: Change ci-test to the name of your environment in environment.yml
script:
  - docker exec -it server_1 py.test test_validate.py
