name: skin_app
dependencies:
        - python = 3.6
        - numpy
        - scipy                                      
        - pandas             
        - pytest                                                          
        - pytest-pep8 
        - pytest-cov
        - sphinx
        - ipython   
        - flask
        - scikit-image
        - openCV
        - pil
